// Bilingual copy dictionary. Keep keys flat & namespaced.
// Anything user-facing in the design lives here.

const I18N = {
  en: {
    'nav.platforms': 'Platforms',
    'nav.capabilities': 'Capabilities',
    'nav.industries': 'Industries',
    'nav.academy': 'Academy',
    'nav.workshop': 'Workshop',
    'nav.lab': 'Lab',
    'nav.news': 'News',
    'nav.contact': 'Contact',
    'nav.brief': 'Mission brief',

    'hero.tag': 'Engineering practice · est. 2026',
    'hero.title.a': 'Utility unmanned',
    'hero.title.b': 'systems,',
    'hero.title.italic': 'responsibly',
    'hero.title.c': 'built.',
    'hero.body': 'A vertically-integrated UAV practice in Costa Rica. Mission-tailored design, in-house manufacturing, full operations support — through to certified decommissioning of every airframe we put in the air.',
    'hero.cta.brief': 'Request a mission brief →',
    'hero.cta.platforms': 'See platforms',
    'hero.fig': 'FIG. 01 · TRAJECTORY',
    'hero.fig.sub': 'S2F-X1 · COSTA RICA · DEMO LOOP',
    'hero.stat.span': 'WINGSPAN',
    'hero.stat.mtow': 'MTOW',
    'hero.stat.endurance': 'ENDURANCE',

    'practice.eyebrow': 'The practice',
    'practice.title': 'A small, careful aerospace practice — measuring forests, mapping coastlines, inspecting power lines, answering emergencies.',
    'practice.body': 'Sketch2Fly is a Costa Rican engineering studio building utility unmanned aircraft for civilian work. We design every airframe to the mission, manufacture the structure ourselves, integrate the avionics, and stay with the aircraft through training, certification, repair, and the quiet end of its working life.',
    'practice.principle.1.t': 'Tools, not weapons',
    'practice.principle.1.b': 'We build for measurement, inspection, science and emergency response. We do not build platforms designed to harm.',
    'practice.principle.2.t': 'Mission-tailored',
    'practice.principle.2.b': 'Sized, shaped and tuned for each client and each environment. No off-the-shelf compromises.',
    'practice.principle.3.t': 'Whole lifecycle',
    'practice.principle.3.b': 'From the first sketch to the responsible recovery of every component when the aircraft retires.',
    'practice.principle.4.t': 'Built in Central America',
    'practice.principle.4.b': 'Engineered, manufactured and supported from Costa Rica — for the region, by the region.',

    'lifecycle.eyebrow': 'Lifecycle',
    'lifecycle.title': 'Seven stages. One workshop.',
    'lifecycle.sub': 'The complete service we offer each client — from the napkin sketch through to the certified end-of-life of every airframe we deliver.',
    'lifecycle.hint': 'Click a stage for detail',
    'lc.01.t': 'Concept', 'lc.01.es': 'Concepto', 'lc.01.d': 'Mission-driven scoping with the client. Constraints, environment, payload, regulation.', 'lc.01.deliv': 'Mission brief · CONOPS doc',
    'lc.02.t': 'Design', 'lc.02.es': 'Diseño', 'lc.02.d': 'Aerodynamic, structural, propulsion and systems engineering — in-house, parametric.', 'lc.02.deliv': 'CAD package · Performance envelope',
    'lc.03.t': 'Manufacture', 'lc.03.es': 'Fabricación', 'lc.03.d': 'Composite layup, additive structures, machined parts, bonded assembly. Outsourced electronics, in-house airframe.', 'lc.03.deliv': 'Airframe · QA report',
    'lc.04.t': 'Integration', 'lc.04.es': 'Integración', 'lc.04.d': 'Avionics, payloads, communications, calibration. Bench tests through tethered flight.', 'lc.04.deliv': 'Flight-ready aircraft',
    'lc.05.t': 'Operate', 'lc.05.es': 'Operación', 'lc.05.d': 'Pilot training, regulatory certification, mission planning and flight operations support.', 'lc.05.deliv': 'Certified pilot · Ops manual',
    'lc.06.t': 'Sustain', 'lc.06.es': 'Mantener', 'lc.06.d': 'Spares, scheduled maintenance, repair workshop, software updates, fleet health monitoring.', 'lc.06.deliv': 'Service contract · Spares kit',
    'lc.07.t': 'Retire', 'lc.07.es': 'Retirar', 'lc.07.d': 'End-of-life recovery: components reclaimed, batteries handled, structure recycled, paperwork closed.', 'lc.07.deliv': 'Decommissioning certificate',

    'platforms.eyebrow': 'Platforms',
    'platforms.title': 'Three reference architectures. Each one is a starting point — every aircraft we deliver is mission-tailored from here.',
    'platforms.cta': 'View tech sheet →',
    'p.x1.name': 'S2F-X1', 'p.x1.tag': 'Quad · Survey',
    'p.x1.desc': 'Compact composite quadcopter for mapping, multispectral and tropical fieldwork. The everyday workhorse.',
    'p.h1.name': 'S2F-H1', 'p.h1.tag': 'Hybrid VTOL · Long range',
    'p.h1.desc': 'Vertical takeoff, fixed-wing cruise. Coastlines, corridors, watershed surveys at scale.',
    'p.r1.name': 'S2F-R1', 'p.r1.tag': 'Heavy lift · Response',
    'p.r1.desc': 'Modular heavy-lift platform for emergency response, supply drops and instrumented research payloads.',

    'industries.eyebrow': 'Industries',
    'industries.title': 'Built for the people who measure, monitor and respond.',
    'ind.ag.t': 'Agriculture & forestry',
    'ind.ag.b': 'Crop health, canopy structure, yield estimation, plantation inventory and reforestation monitoring.',
    'ind.ag.specs': ['Multispectral · 5-band', 'NDVI / NDRE pipelines', 'Endurance 60–120 min', 'Cloud-forest tested'],
    'ind.en.t': 'Energy & utilities',
    'ind.en.b': 'Power line and substation inspection, photovoltaic array thermal sweeps, hydro intake monitoring.',
    'ind.en.specs': ['Thermal IR · 640×512', 'Visual zoom 30×', 'Beyond-line-of-sight ready', 'IP54 weatherized'],
    'ind.gov.t': 'Public safety & emergency',
    'ind.gov.b': 'Search & rescue, post-disaster damage assessment, wildfire reconnaissance, coastal patrol.',
    'ind.gov.specs': ['Rapid deploy < 4 min', 'Encrypted datalink', 'Night-capable EO/IR', 'Air-droppable supplies'],
    'ind.sci.t': 'Science & research',
    'ind.sci.b': 'Custom payload integration for universities, biological stations and climate research programs.',
    'ind.sci.specs': ['Open payload bay 1.2 kg', 'ROS / MAVLink open', 'Synced telemetry export', 'Calibration service'],
    'ind.inf.t': 'Infrastructure & construction',
    'ind.inf.b': 'Topographic surveys, volumetric measurement, progress monitoring, as-built verification.',
    'ind.inf.specs': ['LiDAR · 200 kHz', 'RTK GNSS · 2 cm', 'Photogrammetry pipeline', 'Site safety integration'],
    'ind.env.t': 'Environment & conservation',
    'ind.env.b': 'Reef mapping, mangrove monitoring, wildlife census, illegal deforestation alerts for protected areas.',
    'ind.env.specs': ['Quiet propulsion', 'Long-range coastal', 'Wildlife-safe altitudes', 'Co-developed with MINAE'],

    'cfg.eyebrow': 'Mission configurator',
    'cfg.title': 'Tell us the mission. We sketch the aircraft.',
    'cfg.sub': 'A first-pass conversation, not a quote. Your selections shape a recommended platform — we follow up with a real engineering brief.',
    'cfg.a': 'A · MISSION', 'cfg.b': 'B · ENVIRONMENT', 'cfg.c': 'C · ENDURANCE', 'cfg.d': 'D · PAYLOAD',
    'cfg.recommended': 'RECOMMENDED PLATFORM',
    'cfg.match': 'MATCH',
    'cfg.send': 'Send this brief →',

    'cfg.mission.0': 'Survey & mapping',
    'cfg.mission.1': 'Inspection',
    'cfg.mission.2': 'Emergency response',
    'cfg.mission.3': 'Research payload',
    'cfg.env.0': 'Tropical lowland',
    'cfg.env.1': 'Highland / cloud forest',
    'cfg.env.2': 'Coastal / marine',
    'cfg.env.3': 'Urban',
    'cfg.end.0': '< 30 min',
    'cfg.end.1': '30–60 min',
    'cfg.end.2': '60–120 min',
    'cfg.end.3': '120+ min',
    'cfg.pl.0': 'RGB camera',
    'cfg.pl.1': 'Multispectral',
    'cfg.pl.2': 'LiDAR',
    'cfg.pl.3': 'Custom science',

    'aw.eyebrow': 'Academy & workshop',
    'aw.title': 'A practice, not just a vendor.',
    'aw.sub': 'We exist to make Central America a hub for unmanned systems — knowledge as much as industry. We train pilots, certify operators, run a working repair workshop and publish what we learn.',
    'aw.academy.t': 'Sketch2Fly Academy',
    'aw.academy.b': 'Pilot training, ground-school, regulatory certification courses and a partnership program with regional universities.',
    'aw.academy.cta': 'Course catalog',
    'aw.workshop.t': 'Workshop & service',
    'aw.workshop.b': 'In-house repair, scheduled maintenance, OEM spares, structural inspection and end-of-life processing for every airframe we deliver.',
    'aw.workshop.cta': 'Service plans',
    'aw.lab.t': 'Sketch2Fly Lab',
    'aw.lab.b': 'Open R&D notes, experimental airframes and joint research projects with universities and government agencies.',
    'aw.lab.cta': 'Lab journal',

    'news.eyebrow': 'Lab journal',
    'news.title': 'Recent notes from the workshop.',
    'news.0.t': 'Composite layup study — high-humidity demolding',
    'news.0.d': 'Notes on bonded-skin demolding at 90 % RH for tropical fabrication.',
    'news.0.tag': 'STRUCTURES',
    'news.1.t': 'Field report — UCR mangrove canopy survey',
    'news.1.d': 'A 14-flight campaign mapping 240 ha of Pacific mangrove with the S2F-X1.',
    'news.1.tag': 'FIELD',
    'news.2.t': 'Open spec — modular payload bay v2',
    'news.2.d': 'Mechanical and electrical interface for our 1.2 kg open payload bay, freely available.',
    'news.2.tag': 'OPEN-SOURCE',

    'contact.eyebrow': 'Mission brief',
    'contact.title': 'Tell us what you need to measure, inspect or answer to.',
    'contact.sub': 'A real engineer reads every brief. Expect a response within five working days with questions, scope and a feasibility note — no boilerplate.',
    'contact.f.name': 'Your name',
    'contact.f.org': 'Organization',
    'contact.f.email': 'Email',
    'contact.f.mission': 'Briefly, the mission',
    'contact.f.send': 'Send brief',
    'contact.detail.where': 'Where we are',
    'contact.detail.where.b': 'San José, Costa Rica · 09.928°N 84.090°W',
    'contact.detail.who': 'Who reads these',
    'contact.detail.who.b': 'Engineering team · founders included',
    'contact.detail.when': 'When you hear back',
    'contact.detail.when.b': 'Within five working days, in English or Spanish',

    'foot.tagline': 'Utility unmanned vehicles · designed, built and operated in Costa Rica',
    'foot.copy': '© 2026 Sketch2Fly · All rights reserved',
  },

  es: {
    'nav.platforms': 'Plataformas',
    'nav.capabilities': 'Capacidades',
    'nav.industries': 'Industrias',
    'nav.academy': 'Academia',
    'nav.workshop': 'Taller',
    'nav.lab': 'Lab',
    'nav.news': 'Notas',
    'nav.contact': 'Contacto',
    'nav.brief': 'Solicitar misión',

    'hero.tag': 'Práctica de ingeniería · est. 2026',
    'hero.title.a': 'Vehículos aéreos',
    'hero.title.b': 'no tripulados,',
    'hero.title.italic': 'responsablemente',
    'hero.title.c': 'construidos.',
    'hero.body': 'Una práctica de ingeniería UAV verticalmente integrada, en Costa Rica. Diseño hecho a la medida de cada misión, fabricación propia, operación, formación — y la retirada certificada de cada aeronave que ponemos en el aire.',
    'hero.cta.brief': 'Solicitar una misión →',
    'hero.cta.platforms': 'Ver plataformas',
    'hero.fig': 'FIG. 01 · TRAYECTORIA',
    'hero.fig.sub': 'S2F-X1 · COSTA RICA · CICLO DEMO',
    'hero.stat.span': 'ENVERGADURA',
    'hero.stat.mtow': 'PESO MTOW',
    'hero.stat.endurance': 'AUTONOMÍA',

    'practice.eyebrow': 'La práctica',
    'practice.title': 'Una práctica aeroespacial pequeña y cuidadosa — para medir bosques, mapear costas, inspeccionar líneas eléctricas y atender emergencias.',
    'practice.body': 'Sketch2Fly es un estudio de ingeniería costarricense que diseña y fabrica aeronaves no tripuladas de uso civil. Diseñamos cada estructura a la medida de la misión, la manufacturamos nosotros mismos, integramos la aviónica y acompañamos al equipo durante toda la vida útil de la aeronave.',
    'practice.principle.1.t': 'Herramientas, no armas',
    'practice.principle.1.b': 'Construimos para medir, inspeccionar, investigar y atender emergencias. No diseñamos plataformas para hacer daño.',
    'practice.principle.2.t': 'Hecho a la misión',
    'practice.principle.2.b': 'Cada aeronave dimensionada y afinada para su cliente y su entorno. Sin compromisos genéricos.',
    'practice.principle.3.t': 'Ciclo completo',
    'practice.principle.3.b': 'Desde el primer boceto hasta la recuperación responsable de cada componente cuando la aeronave se retira.',
    'practice.principle.4.t': 'Hecho en Centroamérica',
    'practice.principle.4.b': 'Diseñado, fabricado y soportado desde Costa Rica — para la región, por la región.',

    'lifecycle.eyebrow': 'Ciclo de vida',
    'lifecycle.title': 'Siete etapas. Un solo taller.',
    'lifecycle.sub': 'El servicio completo que ofrecemos a cada cliente — desde el primer boceto hasta el fin de vida certificado de cada aeronave que entregamos.',
    'lifecycle.hint': 'Haz clic en una etapa para ver detalle',
    'lc.01.t': 'Concepto', 'lc.01.es': 'Concept', 'lc.01.d': 'Definición de la misión con el cliente. Restricciones, entorno, carga útil, regulación.', 'lc.01.deliv': 'Brief · documento CONOPS',
    'lc.02.t': 'Diseño', 'lc.02.es': 'Design', 'lc.02.d': 'Ingeniería aerodinámica, estructural, propulsiva y de sistemas — en casa, paramétrica.', 'lc.02.deliv': 'Paquete CAD · envolvente de vuelo',
    'lc.03.t': 'Fabricación', 'lc.03.es': 'Manufacture', 'lc.03.d': 'Composites, fabricación aditiva, mecanizado y ensamblaje. Aviónica externa, estructura propia.', 'lc.03.deliv': 'Estructura · informe QA',
    'lc.04.t': 'Integración', 'lc.04.es': 'Integration', 'lc.04.d': 'Aviónica, cargas útiles, comunicaciones y calibración. Pruebas de banco hasta vuelo cautivo.', 'lc.04.deliv': 'Aeronave lista para vuelo',
    'lc.05.t': 'Operación', 'lc.05.es': 'Operate', 'lc.05.d': 'Formación de pilotos, certificación regulatoria, planificación y soporte de operaciones.', 'lc.05.deliv': 'Piloto certificado · manual ops',
    'lc.06.t': 'Mantener', 'lc.06.es': 'Sustain', 'lc.06.d': 'Repuestos, mantenimiento programado, taller, actualizaciones y monitoreo de flota.', 'lc.06.deliv': 'Contrato de servicio · kit de repuestos',
    'lc.07.t': 'Retirar', 'lc.07.es': 'Retire', 'lc.07.d': 'Recuperación de fin de vida: componentes, baterías y estructura procesados; documentación cerrada.', 'lc.07.deliv': 'Certificado de baja',

    'platforms.eyebrow': 'Plataformas',
    'platforms.title': 'Tres arquitecturas de referencia. Cada una es un punto de partida — cada aeronave entregada se ajusta a su misión.',
    'platforms.cta': 'Ficha técnica →',
    'p.x1.name': 'S2F-X1', 'p.x1.tag': 'Cuadricóptero · Mapeo',
    'p.x1.desc': 'Cuadricóptero compuesto compacto para mapeo, multispectral y trabajo de campo tropical. La herramienta cotidiana.',
    'p.h1.name': 'S2F-H1', 'p.h1.tag': 'VTOL híbrido · Largo alcance',
    'p.h1.desc': 'Despegue vertical, crucero de ala fija. Costas, corredores y cuencas a gran escala.',
    'p.r1.name': 'S2F-R1', 'p.r1.tag': 'Carga pesada · Respuesta',
    'p.r1.desc': 'Plataforma modular de carga pesada para emergencia, lanzamientos y cargas científicas instrumentadas.',

    'industries.eyebrow': 'Industrias',
    'industries.title': 'Construido para quienes miden, monitorean y responden.',
    'ind.ag.t': 'Agricultura & silvicultura',
    'ind.ag.b': 'Salud de cultivos, estructura de dosel, estimación de rendimiento, inventario de plantaciones y monitoreo de reforestación.',
    'ind.ag.specs': ['Multispectral · 5 bandas', 'Pipelines NDVI / NDRE', 'Autonomía 60–120 min', 'Probado en bosque nuboso'],
    'ind.en.t': 'Energía & utilities',
    'ind.en.b': 'Inspección de líneas eléctricas y subestaciones, barridos térmicos de plantas solares y monitoreo hidroeléctrico.',
    'ind.en.specs': ['Térmica IR · 640×512', 'Zoom visual 30×', 'BVLOS lista', 'IP54 intemperie'],
    'ind.gov.t': 'Seguridad & emergencia',
    'ind.gov.b': 'Búsqueda y rescate, evaluación post-desastre, reconocimiento de incendios y patrullaje costero.',
    'ind.gov.specs': ['Despliegue < 4 min', 'Datalink cifrado', 'EO/IR nocturno', 'Lanzamiento de suministros'],
    'ind.sci.t': 'Ciencia & investigación',
    'ind.sci.b': 'Integración de cargas a medida para universidades, estaciones biológicas y programas climáticos.',
    'ind.sci.specs': ['Bahía abierta 1.2 kg', 'ROS / MAVLink abierto', 'Telemetría exportable', 'Servicio de calibración'],
    'ind.inf.t': 'Infraestructura & construcción',
    'ind.inf.b': 'Levantamientos topográficos, mediciones volumétricas, monitoreo de avance y verificación as-built.',
    'ind.inf.specs': ['LiDAR · 200 kHz', 'RTK GNSS · 2 cm', 'Pipeline fotogramétrico', 'Integración HSE'],
    'ind.env.t': 'Ambiente & conservación',
    'ind.env.b': 'Mapeo de arrecifes, monitoreo de manglares, censos de fauna y alertas de deforestación en áreas protegidas.',
    'ind.env.specs': ['Propulsión silenciosa', 'Largo alcance costero', 'Altitudes seguras para fauna', 'Codesarrollado con MINAE'],

    'cfg.eyebrow': 'Configurador de misión',
    'cfg.title': 'Cuéntanos la misión. Esbozamos la aeronave.',
    'cfg.sub': 'Una primera conversación, no una cotización. Tus selecciones forman una plataforma recomendada — luego seguimos con un brief de ingeniería real.',
    'cfg.a': 'A · MISIÓN', 'cfg.b': 'B · ENTORNO', 'cfg.c': 'C · AUTONOMÍA', 'cfg.d': 'D · CARGA',
    'cfg.recommended': 'PLATAFORMA RECOMENDADA',
    'cfg.match': 'AJUSTE',
    'cfg.send': 'Enviar este brief →',

    'cfg.mission.0': 'Mapeo & topografía',
    'cfg.mission.1': 'Inspección',
    'cfg.mission.2': 'Respuesta a emergencia',
    'cfg.mission.3': 'Carga de investigación',
    'cfg.env.0': 'Trópico bajo',
    'cfg.env.1': 'Altura / bosque nuboso',
    'cfg.env.2': 'Costero / marino',
    'cfg.env.3': 'Urbano',
    'cfg.end.0': '< 30 min',
    'cfg.end.1': '30–60 min',
    'cfg.end.2': '60–120 min',
    'cfg.end.3': '120+ min',
    'cfg.pl.0': 'Cámara RGB',
    'cfg.pl.1': 'Multispectral',
    'cfg.pl.2': 'LiDAR',
    'cfg.pl.3': 'Ciencia a medida',

    'aw.eyebrow': 'Academia & taller',
    'aw.title': 'Una práctica, no solo un proveedor.',
    'aw.sub': 'Existimos para que Centroamérica sea un hub de sistemas no tripulados — en conocimiento tanto como en industria. Formamos pilotos, certificamos operadores, operamos un taller real y publicamos lo que aprendemos.',
    'aw.academy.t': 'Academia Sketch2Fly',
    'aw.academy.b': 'Formación de pilotos, escuela de tierra, certificación regulatoria y un programa de alianza con universidades regionales.',
    'aw.academy.cta': 'Catálogo de cursos',
    'aw.workshop.t': 'Taller & servicio',
    'aw.workshop.b': 'Reparación propia, mantenimiento programado, repuestos OEM, inspección estructural y procesamiento de fin de vida.',
    'aw.workshop.cta': 'Planes de servicio',
    'aw.lab.t': 'Lab Sketch2Fly',
    'aw.lab.b': 'Notas abiertas de I+D, aeronaves experimentales y proyectos conjuntos con universidades y agencias.',
    'aw.lab.cta': 'Bitácora del Lab',

    'news.eyebrow': 'Bitácora',
    'news.title': 'Notas recientes desde el taller.',
    'news.0.t': 'Estudio de laminado — desmolde a alta humedad',
    'news.0.d': 'Notas sobre desmolde de pieles laminadas al 90 % HR para fabricación tropical.',
    'news.0.tag': 'ESTRUCTURAS',
    'news.1.t': 'Reporte de campo — manglares con la UCR',
    'news.1.d': 'Una campaña de 14 vuelos mapeando 240 ha de manglar pacífico con el S2F-X1.',
    'news.1.tag': 'CAMPO',
    'news.2.t': 'Spec abierta — bahía modular de carga v2',
    'news.2.d': 'Interfaz mecánica y eléctrica para nuestra bahía de 1.2 kg, libremente disponible.',
    'news.2.tag': 'OPEN-SOURCE',

    'contact.eyebrow': 'Brief de misión',
    'contact.title': 'Cuéntanos qué necesitas medir, inspeccionar o resolver.',
    'contact.sub': 'Un ingeniero real lee cada brief. Esperá respuesta en cinco días hábiles con preguntas, alcance y una nota de viabilidad — sin boilerplate.',
    'contact.f.name': 'Tu nombre',
    'contact.f.org': 'Organización',
    'contact.f.email': 'Correo',
    'contact.f.mission': 'Brevemente, la misión',
    'contact.f.send': 'Enviar brief',
    'contact.detail.where': 'Dónde estamos',
    'contact.detail.where.b': 'San José, Costa Rica · 09.928°N 84.090°W',
    'contact.detail.who': 'Quién lee esto',
    'contact.detail.who.b': 'El equipo de ingeniería · fundadores incluidos',
    'contact.detail.when': 'Cuándo respondemos',
    'contact.detail.when.b': 'En cinco días hábiles, en español o inglés',

    'foot.tagline': 'Vehículos no tripulados de utilidad · diseñados, construidos y operados en Costa Rica',
    'foot.copy': '© 2026 Sketch2Fly · Todos los derechos reservados',
  },
};

// React context — tiny hook for convenience
const I18nCtx = React.createContext({ lang: 'en', t: (k) => k, setLang: () => {} });
const useI18n = () => React.useContext(I18nCtx);
const I18nProvider = ({ lang, setLang, children }) => {
  const t = React.useCallback((k) => I18N[lang]?.[k] ?? I18N.en[k] ?? k, [lang]);
  return <I18nCtx.Provider value={{ lang, t, setLang }}>{children}</I18nCtx.Provider>;
};

Object.assign(window, { I18N, I18nCtx, useI18n, I18nProvider });
